# Generated by Django 5.1.2 on 2024-10-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
