# Generated by Django 5.1.2 on 2024-10-14 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicapp', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenService',
            fields=[
                ('takenserv_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_name', models.CharField(max_length=300)),
                ('total_price', models.IntegerField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manicapp.client')),
            ],
            options={
                'db_table': 'takenservices',
            },
        ),
        migrations.CreateModel(
            name='FreeDate',
            fields=[
                ('freedate_id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('takenserv_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manicapp.takenservice')),
            ],
            options={
                'db_table': 'freedates',
            },
        ),
    ]
