# Generated by Django 5.1.2 on 2024-10-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicapp', '0004_takenservice_freedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenservice',
            name='status',
        ),
        migrations.AlterField(
            model_name='freedate',
            name='takenserv_id',
            field=models.ForeignKey(db_column='takenserv_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manicapp.takenservice'),
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
