# Generated by Django 5.1.2 on 2024-10-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicapp', '0005_remove_takenservice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='freedate',
            name='freedate_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='takenservice',
            name='takenserv_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
