# Generated by Django 5.1.2 on 2024-10-20 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicapp', '0006_alter_client_client_id_alter_freedate_freedate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsCreatedDate',
            fields=[
                ('sunday_date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'iscreateddates',
            },
        ),
        migrations.RenameField(
            model_name='freedate',
            old_name='takenserv_id',
            new_name='takenserv',
        ),
        migrations.RemoveField(
            model_name='takenservice',
            name='client_id',
        ),
        migrations.AddField(
            model_name='takenservice',
            name='client',
            field=models.ForeignKey(db_column='client_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='manicapp.client'),
            preserve_default=False,
        ),
    ]
