# Generated by Django 5.1.2 on 2024-10-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicapp', '0007_iscreateddate_rename_takenserv_id_freedate_takenserv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsDeletedDate',
            fields=[
                ('monday_date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'isdeleteddates',
            },
        ),
    ]
